#!/bin/bash
#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=vessels
#SBATCH --ntasks=1 
#SBATCH --cpus-per-task=12 
#SBATCH --time=00:20:00 
#SBATCH --output=/home/egmelich/segmentation_models/jobfiles/.output/vesseldetect_%A_%a.out 
#SBATCH --error=/home/egmelich/segmentation_models/jobfiles/.output/vesseldetect_%A_%a.err 

# Activate the virtual environment
source /home/egmelich/segmentation_models/seg_venv/bin/activate

python /home/egmelich/segmentation_models/binary_segmetation.py