program: binary_segmentation.py
method: bayes
project: dice_sweep
metric:
  name: valid_loss
  goal: minimize
parameters:
  learning_rate:
    distribution: uniform
    min: 0.0001
    max: 0.01
  batch_size:
    values: [8, 16, 32]