program: binary_segmentation.py
method: bayes
metric:
  name: valid_loss
  goal: minimize
parameters:
  learning rate:
    distribution: uniform
    min: 0.0001
    max: 0.01
  batch size:
    distribution: choice
    values: [8, 16, 32]